// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaqkxmizbbmhnicgxqke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhcWt4bWl6YmJtaG5pY2d4cWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNDkyMTYsImV4cCI6MjA1MDYyNTIxNn0.Y-aLOmlZnENqK28lrFwzOWDa7mSj5dfMxV9Rlik2EzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);